apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: oficina
type: Opaque
stringData:
  Jwt__Key: "MinhaChaveSuperSecretaComMaisDe256Bits12345678901234567890"
  Jwt__Issuer: "AutoRepairShop"
  Jwt__Audience: "AutoRepairShopUsers"
  Jwt__ExpiresInMinutes: "60"