name: SonarQube Analysis

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: |
            ${{ runner.os }}-sonar

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: SonarQube Begin
        run: >
          dotnet sonarscanner begin
          /k:"AutoRepairShop"
          /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Build solution
        run: dotnet build AutoRepairShop.sln --no-incremental

      - name: SonarQube End
        run: dotnet sonarscanner end
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}